apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: debian-test-vm
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            cdrom:
              bus: sata
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: vm-disk-pvc
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: crownlabs
            chpasswd: { expire: False }
            ssh_pwauth: True