apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: debian-nginx-raw-block
  namespace: cldprog-5-block-vms-tests
spec:
  source:
    http:
      # Se nginx-file-service e' in un altro namespace, sostituisci il namespace nel FQDN
      url: "https://releases.ubuntu.com/26.04/ubuntu-26.04-desktop-amd64.iso"
  contentType: kubevirt
  preallocation: true
  pvc:
    accessModes:
      - ReadWriteOnce
    volumeMode: Block
    resources:
      requests:
        storage: 20Gi
    # Decommenta se il cluster richiede una storage class esplicita
    # storageClassName: rook-ceph-block
