apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: debian-nginx-qcow2
  namespace: tenant-s343884
spec:
  source:
    pvc:
      name: debian-nginx-raw-block
      namespace: cldprog-5-block-vms-tests
  contentType: kubevirt
  preallocation: true
  pvc:
    accessModes:
      - ReadWriteOnce
    volumeMode: Block
    resources:
      requests:
        storage: 20Gi
    # Decommenta se il cluster richiede una storage class esplicita
    # storageClassName: rook-ceph-block
