apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: debian-nginx-qcow2
  namespace: cldprog-5-block-vms-tests
spec:
  source:
    http:
      url: "http://nginx-file-service.cldprog-5-block-vms-tests.svc.cluster.local/debian-13-generic-amd64.qcow2"
  contentType: kubevirt
  preallocation: true
  pvc:
    accessModes:
      - ReadWriteOnce
    volumeMode: Block
    resources:
      requests:
        storage: 10Gi
    # Decommenta se il cluster richiede una storage class esplicita
    # storageClassName: rook-ceph-block
