apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        # 1. Monta la root del PVC come root web di Nginx
        - name: data-volume
          mountPath: /usr/share/nginx/html
        # 2. Monta il file di configurazione
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-nginx # Assicurati che sia il nome corretto del tuo PVC
      - name: config-volume
        configMap:
          name: nginx-autoindex-conf
