apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem # <-- Aggiunto qui
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
